#!/bin/bash

# Simple script to update README and optionally commit changes
# Usage: ./update.sh [commit]

echo "🔄 Updating README.md..."

# Run the Python updater
python3 update_readme.py

if [ $? -ne 0 ]; then
    echo "❌ Failed to update README"
    exit 1
fi

# Check if changes were made
if git diff --quiet README.md; then
    echo "ℹ️  No changes to README.md"
    exit 0
fi

echo "📝 Changes detected in README.md"

# If 'commit' argument is provided, auto-commit
if [ "$1" = "commit" ]; then
    echo "💾 Committing changes..."
    git add README.md
    git commit -m "📝 Update README with latest projects

Auto-generated by update script"
    
    echo "✅ Changes committed!"
    echo "💡 Don't forget to push: git push origin main"
else
    echo "📋 To commit these changes, run:"
    echo "   git add README.md"
    echo "   git commit -m 'Update README'"
    echo ""
    echo "📋 Or run this script with 'commit' to auto-commit:"
    echo "   ./update.sh commit"
fi 